spring.profiles.active=dev
spring.application.name=portail-doctorat1
server.port=8081

app.upload.dir=./uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB